# Generated by Django 6.0.6 on 2026-06-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='chat_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
